import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { listSessions } from '../services/api'
import { 
  TargetIcon, 
  BrainIcon, 
  DocumentIcon, 
  ArrowRightIcon, 
  RocketIcon, 
  BriefcaseIcon,
  BulbIcon
} from '../components/Icons'

export default function Home() {
  const [sessions, setSessions] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    listSessions()
      .then(data => {
        // Limit to last 6 sessions for a cleaner UI
        const sortedSessions = (data.sessions || []).slice(-6).reverse()
        setSessions(sortedSessions)
        setLoading(false)
      })
      .catch(err => {
        console.error("Failed to load sessions:", err)
        setLoading(false)
      })
  }, [])

  return (
    <div className="page fade-in">
      {/* Hero Section */}
      <section className="home-hero-container">
        <div className="home-hero-content">
          <div className="home-hero-badge">
            <RocketIcon size={14} style={{ marginRight: '0.25rem' }} />
            AI-Powered Preparation
          </div>
          <h1>Ace Your Next <br /><span>Tech Interview</span></h1>
          <p>
            Practice with our intelligent AI interviewer. Get tailored questions based on your target role and resume, with detailed feedback on every answer.
          </p>
          <Link to="/interview" className="home-cta-btn">
            Start New Interview
            <ArrowRightIcon size={18} />
          </Link>
        </div>
        
        <div className="home-hero-image-wrap">
          <img 
            src="/hero_illustration.png" 
            alt="AI Interview Illustration" 
            className="home-hero-image" 
          />
        </div>
      </section>

      {/* Feature Section */}
      <section className="home-features">
        <div className="feature-card">
          <div className="feature-icon-badge">
            <TargetIcon size={24} />
          </div>
          <h3>Role Specific</h3>
          <p>Questions tailored exactly to the job description and title you are targeting.</p>
        </div>
        
        <div className="feature-card">
          <div className="feature-icon-badge">
            <BrainIcon size={24} />
          </div>
          <h3>AI Feedback</h3>
          <p>Real-time analysis on clarity, relevance, and the STAR method.</p>
        </div>
        
        <div className="feature-card">
          <div className="feature-icon-badge">
            <DocumentIcon size={24} />
          </div>
          <h3>Resume Context</h3>
          <p>The AI reviews your resume to ask personalized follow-up questions.</p>
        </div>
      </section>

      {/* Intro / How It Works Flow */}
      <section className="intro-flow-section">
        <h2 className="section-title">How It Works</h2>
        <p className="section-subtitle">Follow four simple steps to prepare and evaluate your skills in a sandbox interview environment.</p>
        
        <div className="flow-grid">
          <div className="flow-step">
            <span className="flow-number">1</span>
            <BriefcaseIcon className="flow-icon" size={32} />
            <h3>Configure Role</h3>
            <p>Enter your target job role, optional description, and upload a resume.</p>
          </div>
          
          <div className="flow-step">
            <span className="flow-number">2</span>
            <BrainIcon className="flow-icon" size={32} />
            <h3>Mock Session</h3>
            <p>Engage in a simulated 10-question chat interview generated by the AI.</p>
          </div>
          
          <div className="flow-step">
            <span className="flow-number">3</span>
            <BulbIcon className="flow-icon" size={32} />
            <h3>Get Feedback</h3>
            <p>Receive live ratings on clarity, relevance, and STAR scores for every reply.</p>
          </div>
          
          <div className="flow-step">
            <span className="flow-number">4</span>
            <DocumentIcon className="flow-icon" size={32} />
            <h3>PDF Report</h3>
            <p>Download a comprehensive, stylized PDF evaluation of your entire performance.</p>
          </div>
        </div>
      </section>

      {/* Past Sessions */}
      <section className="sessions-section">
        <h2>Recent Interview Sessions</h2>
        {loading ? (
          <div className="sessions-empty">Loading your sessions...</div>
        ) : sessions.length > 0 ? (
          <ul className="sessions-list">
            {sessions.map((s, i) => (
              <li key={i} className="session-item">
                <div>
                  <span className="session-meta-role">💼 {s.job_role || 'General'}</span>
                  <span className="session-meta-id">ID: {s.id}</span>
                </div>
                {s.overall_score && (
                  <div className="session-score-indicator">
                    ★ {s.overall_score.toFixed(1)} / 5.0
                  </div>
                )}
              </li>
            ))}
          </ul>
        ) : (
          <div className="sessions-empty">
            No previous sessions found. Start a new interview to see your history here!
          </div>
        )}
      </section>
    </div>
  )
}
